# Mandatory Header
modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/Mestre-Tramador/Mo-Creatures-Redux-Redone/issues/"


[[mods]]
# Mod basic info
modId="mocreaturesrr"
displayName="Mo'Creatures Redux&Redone"
version="0.0.0.1"

# Body texts
description='''
Mo'Creatures Redux&Redone is an attempt to recreate DrZharks' Mo'Creatures in the new versions of Minecraft with redesigned ideas.'''
authors="Mestre Tramador"
credits="Thanks to DrZharks and all contributors of the original mod; all Forge team, for the modding suppor; and Minecraft, for everything else."

# Details
displayURL="https://github.com/Mestre-Tramador/Mo-Creatures-Redux-Redone/" # TODO: Update to a GitHub Page
#logoFile="examplemod.png"
#updateJSONURL="https://change.me.example.invalid/updates.json"

# Forge Dependency specs
[[dependencies.mocreaturesrr]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

# Minecraft Dependency specs
[[dependencies.mocreaturesrr]]
modId="minecraft"
mandatory=true
versionRange="[1.17,1.18)"
ordering="NONE"
side="BOTH"