########################################################################
# This shell script file creates a Lang Data Generator class.
# It does not create a Constant for the Lang ID.
# Neither add it in the Data Generation class.
#
# Please be gentle with this code.
########################################################################

# Gloval variables.
version="0.0.29"
author="Eduardo de Oliveira Rosa, Mestre Tramador."


# Get all the directories to save the files.
modeldir="../src/main/java/mestretramador/rrmocreatures/data/client/lang"


# Collect the lang new name.
set +v
echo "What will be the Lang class name?"
echo "The Lang class name must be in Pascal Case eg. \"NewLangClass\"."
read -p "Lang: " class
if [ -z "$class" ]
then
    exit
fi

# Collect the lang ID constant.
echo
echo "What is the Lang ID constant?"
echo "The Lang ID constant must be in Upper case and Underscores eg. \"LOCAL_E\"."
read -p "ID: " id
if [ -z "$id" ]
then
    exit
fi

# Collect the lang name.
echo
echo "What is the Lang name?"
echo "The Lang name is generally the same as the class name but with spaces eg. \"Local (E)\"."
read -p "Name: " name
if [ -z "$name" ]
then
    exit
fi


# Go to the Lang directory.
cd "$modeldir"

# Create the Lang.
touch "RRMoCLang$class.java"
chmod 744 "RRMoCLang$class.java"

echo "package mestretramador.rrmocreatures.data.lang;                                       " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "import mestretramador.rrmocreatures.data.provider.RRMoCLangProvider;                  " >> "RRMoCLang$class.java"
echo "import mestretramador.rrmocreatures.init.RegisterBlock;                               " >> "RRMoCLang$class.java"
echo "import mestretramador.rrmocreatures.init.RegisterItem;                                " >> "RRMoCLang$class.java"
echo "import mestretramador.rrmocreatures.util.Constants;                                   " >> "RRMoCLang$class.java"
echo "import mestretramador.rrmocreatures.util.Tabs;                                        " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "import net.minecraft.data.DataGenerator;                                              " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "/**                                                                                   " >> "RRMoCLang$class.java"
echo " * Mo^'Creatures Redux^&Redone $name translator.                                      " >> "RRMoCLang$class.java"
echo " *                                                                                    " >> "RRMoCLang$class.java"
echo " * @version $version                                                                  " >> "RRMoCLang$class.java"
echo " * @author $author                                                                    " >> "RRMoCLang$class.java"
echo " */                                                                                   " >> "RRMoCLang$class.java"
echo "public class RRMoCLang$class extends RRMoCLangProvider                                " >> "RRMoCLang$class.java"
echo "{                                                                                     " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Using the parent constructor to provide $name support,                         " >> "RRMoCLang$class.java"
echo "     * just pass a Data Generator.                                                    " >> "RRMoCLang$class.java"
echo "     *                                                                                " >> "RRMoCLang$class.java"
echo "     * @param generator Minecraft {@link net.minecraft.data.DataGenerator             " >> "RRMoCLang$class.java"
echo "     *                  Data Generator}.                                              " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    public RRMoCLang$class(DataGenerator generator)                                   " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        super(generator, Constants.Langs.$id);                                        " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Register all lang entries.                                                     " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    @Override                                                                         " >> "RRMoCLang$class.java"
echo "    protected void addTranslations()                                                  " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        BLOCKS.forEach((block, translation) -> {                                      " >> "RRMoCLang$class.java"
echo "            add(block, translation);                                                  " >> "RRMoCLang$class.java"
echo "        });                                                                           " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "        ITEMS.forEach((item, translation) -> {                                        " >> "RRMoCLang$class.java"
echo "            add(item, translation);                                                   " >> "RRMoCLang$class.java"
echo "        });                                                                           " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "        MUSIC_DISCS.forEach((item, translation) -> {                                  " >> "RRMoCLang$class.java"
echo "            add(getMusicDiscTranslationKey(item.getTranslationKey()), translation);   " >> "RRMoCLang$class.java"
echo "        });                                                                           " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "        TABS.forEach((tab, translation) -> {                                          " >> "RRMoCLang$class.java"
echo "            add(getItemGroupTranslationKey(tab.getPath()), translation);              " >> "RRMoCLang$class.java"
echo "        });                                                                           " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Translate all Blocks to $name.                                                 " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    @Override                                                                         " >> "RRMoCLang$class.java"
echo "    protected void setBlocks()                                                        " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        // * Last actualization in 09/11/2020                                         " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_DIRT.returnAsBlock(), \"\");               " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_GRASS.returnAsBlock(), \"\");              " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_LEAVES.returnAsBlock(), \"\");             " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_LOG.returnAsBlock(), \"\");                " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_PLANKS.returnAsBlock(), \"\");             " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_STONE.returnAsBlock(), \"\");              " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.OGRE_LAIR_TALL_GRASS.returnAsBlock(), \"\");         " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_DIRT.returnAsBlock(), \"\");             " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_GRASS.returnAsBlock(), \"\");            " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_LEAVES.returnAsBlock(), \"\");           " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_LOG.returnAsBlock(), \"\");              " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_PLANKS.returnAsBlock(), \"\");           " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_STONE.returnAsBlock(), \"\");            " >> "RRMoCLang$class.java"
echo "        BLOCKS.put(RegisterBlock.WYVERN_LAIR_TALL_GRASS.returnAsBlock(), \"\");       " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Translate all Items to $name.                                                  " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    @Override                                                                         " >> "RRMoCLang$class.java"
echo "    protected void setItems()                                                         " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        // * Last actualization in 09/11/2020                                         " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_BONE.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_BONE_FILLED.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_FAIRY.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_FAIRY_FILLED.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_GHOST.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_GHOST_FILLED.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_GUARDIAN.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_GUARDIAN_FILLED.returnAsItem(), \"\");          " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_SKY.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.AMULET_SKY_FILLED.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.BIGCAT_CLAW.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DARK.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DARK_BOOTS.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DARK_CHEST.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DARK_HELMET.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DARK_LEGS.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DIRT.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DIRT_BOOTS.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DIRT_CHEST.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DIRT_HELMET.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_DIRT_LEGS.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_FROST.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_FROST_BOOTS.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_FROST_CHEST.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_FROST_HELMET.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_FROST_LEGS.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_NETHER.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_NETHER_BOOTS.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_NETHER_CHEST.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_NETHER_HELMET.returnAsItem(), \"\");            " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CHITIN_NETHER_LEGS.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CRAB_COOKED.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CRAB_RAW.returnAsItem(), \"\");                        " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.CREATURE_PEDIA.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.EGG_HATCHABLE.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.EGG_HATCHABLE_OMELET.returnAsItem(), \"\");            " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_CHEST.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_HARNESS.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_INDIAN_GARMENT.returnAsItem(), \"\");         " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_INDIAN_HOWDAH.returnAsItem(), \"\");          " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_MAMMOTH_PLATFORM.returnAsItem(), \"\");       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_TUSKS_DIAMOND.returnAsItem(), \"\");          " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_TUSKS_IRON.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ELEPHANT_TUSKS_WOOD.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ESSENCE_DARKNESS.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ESSENCE_FIRE.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ESSENCE_LIGHT.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.ESSENCE_UNDEAD.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FISH_NET.returnAsItem(), \"\");                        " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FISH_NET_FILLED.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FUR.returnAsItem(), \"\");                             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FUR_BOOTS.returnAsItem(), \"\");                       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FUR_CHEST.returnAsItem(), \"\");                       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FUR_HELMET.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.FUR_LEGS.returnAsItem(), \"\");                        " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_LEAD.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_MOUNT_ARMOR_CRYSTAL.returnAsItem(), \"\");    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_MOUNT_ARMOR_DIAMOND.returnAsItem(), \"\");    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_MOUNT_ARMOR_GOLD.returnAsItem(), \"\");       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_MOUNT_ARMOR_IRON.returnAsItem(), \"\");       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_MOUNT_ARMOR_LEATHER.returnAsItem(), \"\");    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_SADDLE.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HANDMADE_SADDLE_CHEST.returnAsItem(), \"\");           " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HEART_DARKNESS.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HEART_FIRE.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HEART_UNDEAD.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HIDE.returnAsItem(), \"\");                            " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HIDE_BOOTS.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HIDE_CHEST.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HIDE_HELMET.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.HIDE_LEGS.returnAsItem(), \"\");                       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KEY.returnAsItem(), \"\");                             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED.returnAsItem(), \"\");                       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_BLACK.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_BLUE.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_BROWN.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_CYAN.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_GRAY.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_GREEN.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_LIGHT_BLUE.returnAsItem(), \"\");            " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_LIGHT_GRAY.returnAsItem(), \"\");            " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_LIME.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_MAGENTA.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_ORANGE.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_PINK.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_PURPLE.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_RED.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_WHITE.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_BED_YELLOW.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_FOOD.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_LITTER.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.KITTY_WOOL_BALL.returnAsItem(), \"\");                 " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.MEDALLION.returnAsItem(), \"\");                       " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.OGRE_LAIR_PRINCE_CANNON_FIRE.returnAsItem(), \"\");    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.OGRE_LAIR_PRINCE_HAMMER_BUILDER.returnAsItem(), \"\"); " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.OGRE_LAIR_PRINCE_STAFF_TELEPORT.returnAsItem(), \"\"); " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.OSTRICH_COOKED.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.OSTRICH_RAW.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.RAT_BURGER.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.RAT_COOKED.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.RAT_RAW.returnAsItem(), \"\");                         " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.RECORD_ZEBRA.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.REPTILE_HIDE.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.REPTILE_HIDE_BOOTS.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.REPTILE_HIDE_CHEST.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.REPTILE_HIDE_HELMET.returnAsItem(), \"\");             " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.REPTILE_HIDE_LEGS.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SCROLL_BLANK.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SCROLL_FREEDOM.returnAsItem(), \"\");                  " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SCROLL_OWNER.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SCROLL_SALE.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SHARK_TEETH.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SHARK_TEETH_SWORD.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SILVER_SKELETON_SWORD.returnAsItem(), \"\");           " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STAFF_BASE.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STAFF_DIAMOND.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STAFF_ENDER.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STAFF_LIGHT.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_DARK.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_DARK_SWORD.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_DIRT.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_DIRT_SWORD.returnAsItem(), \"\");                " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_FROST.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_FROST_SWORD.returnAsItem(), \"\");               " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_NETHER.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.STING_NETHER_SWORD.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.SUGAR_LUMP.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TMNT_BO.returnAsItem(), \"\");                         " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TMNT_KATANA.returnAsItem(), \"\");                     " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TMNT_NUNCHAKU.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TMNT_SAI.returnAsItem(), \"\");                        " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TURKEY_COOKED.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TURKEY_RAW.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TURTLE_COOKED.returnAsItem(), \"\");                   " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TURTLE_COOKED_SOUP.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.TURTLE_RAW.returnAsItem(), \"\");                      " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.UNICORN_HORN.returnAsItem(), \"\");                    " >> "RRMoCLang$class.java"
echo "        ITEMS.put(RegisterItem.WHIP.returnAsItem(), \"\");                            " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Translate all Music Discs to $name.                                            " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    @Override                                                                         " >> "RRMoCLang$class.java"
echo "    protected void setMusicDiscs()                                                    " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        // * Last actualization in 11/11/2020                                         " >> "RRMoCLang$class.java"
echo "        MUSIC_DISCS.put(RegisterItem.RECORD_ZEBRA.returnAsItem(), \"\");              " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "                                                                                      " >> "RRMoCLang$class.java"
echo "    /**                                                                               " >> "RRMoCLang$class.java"
echo "     * Translate all Tabs to $name.                                                   " >> "RRMoCLang$class.java"
echo "     */                                                                               " >> "RRMoCLang$class.java"
echo "    @Override                                                                         " >> "RRMoCLang$class.java"
echo "    protected void setTabs()                                                          " >> "RRMoCLang$class.java"
echo "    {                                                                                 " >> "RRMoCLang$class.java"
echo "        // * Last actualization in 29/11/2020                                         " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.ANIMALSTUFF, \"\");                                             " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.BLOCKS, \"\");                                                  " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.COMBAT, \"\");                                                  " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.EGGS, \"\");                                                    " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.FOOD, \"\");                                                    " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.MAGIC, \"\");                                                   " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.MATERIALS, \"\");                                               " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.MISC, \"\");                                                    " >> "RRMoCLang$class.java"
echo "        TABS.put(Tabs.TOOLS, \"\");                                                   " >> "RRMoCLang$class.java"
echo "    }                                                                                 " >> "RRMoCLang$class.java"
echo "}                                                                                     " >> "RRMoCLang$class.java"

# Add the Lang in Git.
git add RRMoCLang$class.java


# Final message.
echo
echo "Created Lang for $name!"
echo "Plase insert it on and run Data Generation."
read -s -n 1 -p "Press any key to continue . . ."
echo ""